### ISSUE TITLE
Chinese supported?

### ISSUE THREAD

**Issue by lucasjinreal** [liusongxiang/efficient_tts#1]
Does it supported Chinese?

**Comment by liusongxiang** [comment]
Yes. The paper reports good results on an open-source standard Mandarin dataset. 
But currently this repo tunes on LJ-speech.

**Comment by lucasjinreal** [comment]
@liusongxiang Will it plan to support Biaobei dataset as well? Which maybe helpful for China ttsers.

**Comment by liusongxiang** [comment]
It's convenient to adapt the lj-speech example to the Biaobei dataset. I will do it if I have time. Help is welcome!

**Comment by liusongxiang** [comment]
Hi, for your information, Mandarin  generated samples can be found at https://github.com/liusongxiang/efficient_tts/tree/main/egs/DataBaker/checkpoint-330000steps_LJ_vocoder.

**Comment by lucasjinreal** [comment]
@liusongxiang thank u! it sounds very nice! Do u have a inference speed record of it? Compare with tacotron2

**Comment by liusongxiang** [comment]
https://github.com/liusongxiang/efficient_tts/issues/4#issuecomment-747942993
