### ISSUE TITLE
questions about code

### ISSUE THREAD

**Issue by attitudechunfeng** [liusongxiang/efficient_tts#3]
I wonder if the code in https://github.com/liusongxiang/efficient_tts/blob/d186a56bf87e2c688158179f0f41b981718aebdb/nntts/models/efficient_tts.py#L338 is correct？It seems two tensors with different size make subtraction，[B,T2,1] and [B,T1,1]

**Comment by liusongxiang** [comment]
imv.unsqueeze(1) has shape of [B, 1, T2] and p.unsqueeze(-1) has shape of [B, T1, 1].
The minus operation will conduct broadcast first, which means the result will have shape of [B, T1, T2].

**Comment by attitudechunfeng** [comment]
got it, thank you!
